export const ACTION_ROUTE = "SearchToolIndex";
//字典项获取
export const DIC_GET_PARLIST = 'DIC_GET_PARLIST';
export const DIC_GET_PARLIST_COMPLETE = 'DIC_GET_PARLIST_COMPLETE';
export const DIC_GET_AREA = 'DIC_GET_AREA';
export const DIC_GET_AREA_COMPLETE = 'DIC_GET_AREA_COMPLETE';

//查询处理
export const SEARCH_XYH_BUILDING = 'SEARCH_XYH_BUILDING';//新耀行楼盘查询
export const SEARCH_XYH_BUILDING_COMPLETE = 'SEARCH_XYH_BUILDING_COMPLETE';//查询完成
export const XYH_GET_BUILDING_DETAIL = 'XYH_GET_BUILDING_DETAIL';
export const XYH_GET_BUILDING_COMPLETE = 'XYH_GET_BUILDING_COMPLETE';//楼盘详细
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';//设置遮罩层
export const SEARCH_BOX_EXPAND = 'SEARCH_BOX_EXPAND';//搜索条件展开
export const GET_BUILDING_SHOPS = 'GET_BUILDING_SHOPS';//获取楼盘商铺列表
export const GET_BUILDING_SHOPS_COMPLETE = 'GET_BUILDING_SHOPS_COMPLETE';//获取楼盘商铺详细
export const GET_BUILDING_SHOPS_DETAIL = 'GET_BUILDING_SHOPS_DETAIL';//获取楼盘详细
export const GET_BUILDING_SHOPS_DETAIL_COMPLETE = 'GET_BUILDING_SHOPS_DETAIL_COMPLETE';//获取楼盘详细完成
//查询结果处理
export const RESULT_PREV = "RESULT_PREV";
export const RESULT_NEXT = "RESULT_NEXT";
export const RESULT_PREV_COMPLETE = "RESULT_PREV_COMPLETE";
export const RESULT_NEXT_COMPLETE = "RESULT_NEXT_COMPLETE";
export const RESULT_CLOSE = "RESULT_CLOSE";
export const RESULT_BUILDING_RECOMMEND = 'RESULT_BUILDING_RECOMMEND';//楼盘推荐
export const RESULT_VIEW_BACK = 'RESULT_VIEW_BACK';//详细查看回退
//权限判断
export const GET_RECOMMEND_PERMISSION = 'GET_RECOMMEND_PERMISSION';//推荐权限判断
export const GET_PERMISSION_COMPLETE = 'GET_PERMISSION_COMPLETE';
//推荐相关
export const OPEN_RECOMMEND_DIALOG = 'OPEN_RECOMMEND_DIALOG';
export const CLOSE_RECOMMEND_DIALOG = 'CLOSE_RECOMMEND_DIALOG';
export const GET_RECOMMEND_LIST = 'GET_RECOMMEND_LIST';//获取推荐列表
export const GET_RECOMMEND_LIST_COMPLETE = 'GET_RECOMMEND_LIST_COMPLETE';//
export const CANCEL_RECOMMEND = 'CANCEL_RECOMMEND';//取消推荐
//成交信息
export const GET_CUSTOMER_DEAL_INFO = 'GET_CUSTOMER_DEAL_INFO';//
export const GET_CUSTOMER_DEAL_INFO_COMPLETE = 'GET_CUSTOMER_DEAL_INFO_COMPLETE';//
//跑马灯消息
export const OPEN_MSG_LIST = 'OPEN_MSG_LIST';
export const OPEN_MSG_DETAIL = 'OPEN_MSG_DETAIL';
export const GET_MSG_LIST = 'GET_MSG_LIST';
export const GET_MSG_LIST_COMPLETE = 'GET_MSG_LIST_COMPLETE';
export const GET_MSG_DETAIL = 'GET_MSG_DETAIL';
export const GET_MSG_DETAIL_COMPLETE = 'GET_MSG_DETAIL_COMPLETE';
//导航处理
export const NAV_CHANGE = 'NAV_CHANGE';
// 获取房源动态列表
export const GET_ACTIVE_LIST = 'GET_ACTIVE_LIST';
export const GET_ACTIVE_LIST_START = 'GET_ACTIVE_LIST_START';
export const GET_ACTIVE_LIST_END = 'GET_ACTIVE_LIST_END';