import React from 'react';
import ReactDOM from 'react-dom';
import * as Redux from 'redux';
import * as ReactRouter from 'react-router';
import * as oidc from 'redux-oidc';
import {routerMiddleware } from 'react-router-redux';
import * as ReactRedux from 'react-redux';
import * as DynamicReducer from 'redux-dynamic-reducer';
import * as ReduxSaga from 'redux-saga';
import * as Loadable from 'react-loadable';
import {Button, Form, Modal, Input, Avatar, Icon, Checkbox, Badge, Affix, Menu, Dropdown} from 'antd';
import * as ResizeAware from 'react-resize-aware';