

export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';
export const LOAD_SUBSCRIPTIONS_START = 'redux-oidc-sample/LOAD_SUBSCRIPTIONS_START';
export const LOAD_SUBSCRIPTIONS_SUCCESS = 'redux-oidc-sample/LOAD_SUBSCRIPTIONS_SUCCESS';

export const WINDOWS_OPEN_NEW = 'WINDOWS_OPEN_NEW';
export const WINDOWS_CLOSE = 'WINDOWS_CLOSE';
export const WINDOWS_RESTORE = 'WINDOWS_RESTORE';
export const WINDOWS_ACTIVE = 'WINDOWS_ACTIVE';
export const WINDOWS_MAXIMIZE = 'WINDOWS_MAXIMIZE';
export const WINDOWS_MINIMIZE = 'WINDOWS_MINIMIZE';
export const WINDOWS_RESTORE_X = 'WINDOWS_RESTORE_X';
export const WINDOWS_OPENORACTIVE = 'WINDOWS_OPENORACTIVE';

//字典项获取
export const DIC_GET_PARLIST = '@DIC_GET_PARLIST';
export const DIC_GET_PARLIST_COMPLETE = '@DIC_GET_PARLIST_COMPLETE';
export const DIC_GET_AREA = '@DIC_GET_AREA';
export const DIC_GET_AREA_COMPLETE = '@DIC_GET_AREA_COMPLETE';

//应用相关
export const APP_LIST_GET = 'APP_LIST_GET';
export const APP_LIST_UPDATE = 'APP_LIST_UPDATE';

//修改密码
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const CLOSE_PASSWORD = 'CLOSE_PASSWORD';

//遮罩层
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
//系统消息
export const GET_UNREAD_COUNT = 'GET_UNREAD_COUNT';
export const GET_UNREAD_COUNT_COMPLETE = 'GET_UNREAD_COUNT_COMPLETE';
export const GET_RECEIVE_LIST = 'GET_RECEIVE_LIST';
export const GET_RECEIVE_LIST_COMPLETE = 'GET_RECEIVE_LIST_COMPLETE';
export const GET_SYS_MSG_DETAIL = 'GET_SYS_MSG_DETAIL';//获取消息详细
export const GET_SYS_MSG_DETAIL_COMPLETE = 'GET_SYS_MSG_DETAIL_COMPLETE';
//权限判断
export const JUDGE_PERMISSION = 'JUDGE_PERMISSION';//权限判断
export const JUDGE_PERMISSION_COMPLETE = 'JUDGE_PERMISSION_COMPLETE';