export const ACTION_ROUTE = "ContractManagementIndex";

//字典项获取
export const DIC_GET_PARLIST = 'DIC_GET_PARLIST';
export const DIC_GET_PARLIST_COMPLETE = 'DIC_GET_PARLIST_COMPLETE';
export const DIC_GET_AREA = 'DIC_GET_AREA';
export const DIC_GET_AREA_COMPLETE = 'DIC_GET_AREA_COMPLETE';
export const DIC_GET_ORG_LIST = 'DIC_GET_ORG_LIST';//获取部门数据
export const DIC_GET_ORG_LIST_COMPLETE = 'DIC_GET_ORG_LIST_COMPLETE';
export const DIC_GET_ORG_DETAIL = 'DIC_GET_ORG_DETAIL';//获取部门详细数据
export const DIC_GET_ORG_DETAIL_COMPLETE = 'DIC_GET_ORG_DETAIL_COMPLETE';
export const GET_ORG_USERLIST = 'GET_ORG_USERLIST';//获取部门用户列表
export const GET_ORG_USERLIST_COMPLETE = 'GET_ORG_USERLIST_COMPLETE';//获取部门用户列表
export const DIC_GET_ALL_ORG_LIST = 'DIC_GET_ALL_ORG_LIST';
export const DIC_GET_ALL_ORG_LIST_COMPLETE = 'DIC_GET_ALL_ORG_LIST_COMPLETE';








//合同文件上传
export const OPEN_ATTACHMENT = 'OPEN_ATTACHMENT'; //打开合同上传页
export const OPEN_ATTACHMENT_START = 'OPEN_ATTACHMENT_START';
export const OPEN_ATTACHMENT_FINISH = 'OPEN_ATTACHMENT_FINISH';
export const CLOSE_ATTACHMENT = 'CLOSE_ATTACHMENT';//关闭合同上传页
export const UPLOAD_ATTCHMENT_LIST = 'UPLOAD_ATTCHMENT_LIST';//上传附件
export const UPLOAD_ATTCHMENT_LIST_COMPLETE = 'UPLOAD_ATTCHMENT_LIST_COMPLETE';//上传附件完成

//合同录入
export const OPEN_RECORD = 'OPEN_RECORD'; //打开合同录入页
export const OPEN_RECORD_NAVIGATOR = 'OPEN_RECORD_NAVIGATOR';
export const CLOSE_RECORD = 'CLOSE_RECORD';//关闭合同录入页
export const CONTRACT_INFO_SUBMIT = 'CONTRACT_INFO_SUBMIT';//提交合同信息
export const CONTRACT_INFO_SUBMIT_START = 'CONTRACT_INFO_SUBMIT_START';//开始提交合同信息
export const CONTRACT_INFO_SUBMIT_FINISH = 'SUBMIT_CONTRACT_INFO_COMPLETE';//提交合同信息完成
export const CLEAR_CONTRACT_INFO = 'CLEAR_CONTRACT_INFO';//清除合同信息

//导出
export const EXPORT_CONTRACT = 'EXPORT_CONTRACT';
export const EXPORT_CONTRACT_COMPLETE = 'EXPORT_CONTRACT_COMPLETE';
export const EXPORT_MULTI_CONTRACT = 'EXPORT_MULTI_CONTRACT';
export const EXPORT_MULTI_CONTRACT_COMPLETE = 'EXPORT_MULTI_CONTRACT_COMPLETE';


//合同相关
export const CONTRACT_GET_DETAIL = 'CONTRACT_GET_DETAIL';//合同整体信息

export const CONTRACT_BASIC_SAVE = 'CONTRACT_BASIC_SAVE';//合同基础信息保存
export const CONTRACT_BASIC_ADD = 'CONTRACT_BASIC_ADD';//合同基础信息添加
export const CONTRACT_BASIC_EDIT = 'CONTRACT_BASIC_EDIT';//合同基础信息编辑
export const CONTRACT_BASIC_VIEW = 'CONTRACT_BASIC_VIEW';

export const CONTRACT_PICTURE_SAVE = 'CONTRACT_PICTURE_SAVE';//附件图片保存
export const CONTRACT_PICTURE_EDIT = 'CONTRACT_PICTURE_EDIT';
export const CONTRACT_PICTURE_VIEW = 'CONTRACT_PICTURE_VIEW';

export const CONTRACT_FILE_SAVE = 'CONTRACT_PICTURE_SAVE';//附件文件保存
export const CONTRACT_FILE_EDIT = 'CONTRACT_PICTURE_EDIT';
export const CONTRACT_FILE_VIEW = 'CONTRACT_PICTURE_VIEW';

export const LOADING_START_BASIC = 'LOADING_START_BASIC';
export const LOADING_END_BASIC = 'LOADING_END_BASIC';

//临时更改设置当前用户的部门id为当前选择orgid
export const SET_INIT_ACTIVEORG = 'SET_INIT_ACTIVEORG';


//遮罩层
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';//获取待审核列表

//页面切换
export const CHANGE_MENU = 'CHANGE_MENU';//菜单切换


//搜索处理
export const SAVE_SEARCH_CONDITION = 'SAVE_SEARCH_CONDITION';//保存查询条件
export const CHANGE_KEYWORD = 'CHANGE_KEYWORD';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_COMPLETE = 'SEARCH_COMPLETE';


//部门选择
export const OPEN_ORG_SELECT = 'OPEN_ORG_SELECT';//打开部门选择
export const CLOSE_ORG_SELECT = 'CLOSE_ORG_SELECT';//关闭
export const CHAGNE_ACTIVE_ORG = 'CHAGNE_ACTIVE_ORG';//切换部门
export const GOTO_THIS_CONTRACT ='GOTO_THIS_CONTRACT';

//合同详情页
export const GOTO_THIS_CONTRACT_START ='GOTO_THIS_CONTRACT_START';
export const GOTO_THIS_CONTRACT_FINISH ='GOTO_THIS_CONTRACT_FINISH';
export const GOTO_CHANGE_MYADD ='GOTO_CHANGE_MYADD';

//合同详情处理
export const OPEN_CONTRACT_DETAIL = 'OPEN_CONTRACT_DETAIL';//打开详细
export const CLOSE_CONTRACT_DETAIL = 'CLOSE_CONTRACT_DETAIL';//
export const GET_CONTRACT_DETAIL = 'GET_CONTRACT_DETAIL';//
export const GET_CONTRACT_DETAIL_COMPLETE = 'GET_CONTRACT_DETAIL_COMPLETE';//

export const GOTO_THIS_CONTRACT_ATTACH ='GOTO_THIS_CONTRACT_ATTACH';
export const GOTO_THIS_CONTRACT_ATTACH_START ='GOTO_THIS_CONTRACT_ATTACH_START';
export const GOTO_THIS_CONTRACT_ATTACH_FINISH ='GOTO_THIS_CONTRACT_ATTACH_FINISH';

export const INVALIDATE_CONTRACT = 'INVALIDAT_CONTRACTE';//合同作废

//补充协议
export const OPEN_COMPLEMENT = 'OPEN_COMPLEMENT'; //打开合同上传页
export const OPEN_COMPLEMENT_START = 'OPEN_COMPLEMENT_START';
export const OPEN_COMPLEMENT_FINISH = 'OPEN_COMPLEMENT_FINISH';
export const CLOSE_COMPLEMENT = 'CLOSE_COMPLEMENT';//关闭合同上传页
export const CONTRACT_COMPLEMENT_EDIT = 'CONTRACT_COMPLEMENT_EDIT';
export const CONTRACT_COMPLEMENT_SAVE = 'CONTRACT_COMPLEMENT_SAVE';

//合同选择对话框
export const OPEN_CONTRACT_CHOOSE = "OPEN_CONTRACT_CHOOSE";
export const CLOSE_CONTRACT_CHOOSE = "CLOSE_CONTRACT_CHOOSE";

//合同附件上传
export const CONTRACT_PIC_EDIT = 'CONTRACT_PIC_EDIT';//编辑
export const CONTRACT_PIC_VIEW = 'CONTRACT_PIC_VIEW';
export const CONTRACT_SAVE_PICTURE_ASYNC = 'CONTRACT_SAVE_PICTURE_ASYNC';
export const DELETE_PICTURE_ASYNC = 'DELETE_PICTURE_ASYNC';
export const SAVE_DELETE_PIC_LIST = 'SAVE_DELETE_PIC_LIST';
export const SAVE_COMPLETE_FILE_LIST = 'SAVE_COMPLETE_FILE_LIST';


export const LOADING_START_ATTACH = 'LOADING_START_ATTACH';
export const LOADING_END_ATTACH ='LOADING_END_ATTACH';


//历史信息
export const OPEN_MODIFY_HISTORY = 'OPEN_MODIFY_HISTORY';
export const CLOSE_MODIFY_HISTORY = 'CLOSE_MODIFY_HISTORY';


//现在提交完直接返回到首页
export const BASIC_SUBMIT_END = 'BASIC_SUBMIT_END';
export const ATTACH_SUBMIT_END = 'ATTACH_SUBMIT_END';


//甲方
export const COMPANYA_EDIT = 'COMPANYA_EDIT';
export const COMPANYA_ADD = 'COMPANYA_ADD';
export const COMPANYA_SAVE = 'COMPANYA_SAVE';
export const COMPANYA_DELETE = 'COMPANYA_DELETE';

export const COMPANYA_LIST_UPDATE = 'COMPANYA_LIST_UPDATE';
export const COMPANYA_DIALOG_CLOSE = 'COMPANYA_DIALOG_CLOSE';
export const COMPANYA_GET_LIST = 'COMPANYA_GET_LIST';
export const COMPANYA_SERACH_COMPLETE = 'COMPANYA_SERACH_COMPLETE';

//续签记录
export const FOLLOW_HISTORY_DIALOG_CLOSE = 'FOLLOW_HISTORY_DIALOG_CLOSE';
export const FOLLOW_HISTORY_DIALOG_OPEN = 'FOLLOW_HISTORY_DIALOG_OPEN';

//导出全部记录
export const GET_ALL_EXPORT_DATA = 'GET_ALL_EXPORT_DATA';
export const BEGIN_EXPORT_ALL_DATA = 'BEGIN_EXPORT_ALL_DATA';
export const END_EXPORT_ALL_DATA = 'END_EXPORT_ALL_DATA';

//甲方信息窗口
export const GET_ALL_COMPANYA_DATA = 'GET_ALL_COMPANYA_DATA';
export const OPEN_COMPANYA_DIALOG = 'OPEN_COMPANYA_DIALOG';
export const CLOSE_COMPANYA_DIALOG = 'CLOSE_COMPANYA_DIALOG';