export const ACTION_ROUTE = "HumanIndex";

//人事获取
export const GET_ALLHUMANINFO = 'GET_ALLHUMANINFO';
export const UPDATE_ALLHUMANINFO = 'UPDATE_ALLHUMANINFO';

export const GET_DEPARTMENT_ALLHUMANINFO = 'GET_DEPARTMENT_ALLHUMANINFO';
export const UPDATE_DEPARTMENT_ALLHUMANINFO = 'UPDATE_DEPARTMENT_ALLHUMANINFO';
export const HUMAN_GET_DETAIL = 'HUMAN_GET_DETAIL';
export const HUMAN_GET_DETAIL_END = 'HUMAN_GET_DETAIL_END';
//工号
export const GET_HUMANINFONUMBER = 'GET_HUMANINFONUMBER';
export const SET_HUMANINFONUMBER = 'SET_HUMANINFONUMBER';

//人事提交
export const POST_HUMANINFO = 'POST_HUMANINFO';

export const SET_SELHUMANINFO = "SET_SELHUMANINFO";

export const GET_HUMANIMAGE = "GET_HUMANIMAGE";
export const UPDATE_HUMANIMAGE = "UPDATE_HUMANIMAGE";

//字典项获取
export const DIC_GET_ALL_ORG_LIST_COMPLETE = 'DIC_GET_ALL_ORG_LIST_COMPLETE';
export const DIC_GET_PARLIST = 'DIC_GET_PARLIST';
export const DIC_GET_PARLIST_COMPLETE = 'DIC_GET_PARLIST_COMPLETE';
export const DIC_GET_AREA = 'DIC_GET_AREA';
export const DIC_GET_AREA_COMPLETE = 'DIC_GET_AREA_COMPLETE';
export const DIC_GET_ORG_LIST = 'DIC_GET_ORG_LIST';//获取部门数据
export const DIC_GET_ORG_LIST_COMPLETE = 'DIC_GET_ORG_LIST_COMPLETE';
export const DIC_GET_ORG_DETAIL = 'DIC_GET_ORG_DETAIL';//获取部门详细数据
export const DIC_GET_ORG_DETAIL_COMPLETE = 'DIC_GET_ORG_DETAIL_COMPLETE';
export const GET_ORG_USERLIST = 'GET_ORG_USERLIST';//获取部门用户列表
export const GET_ORG_USERLIST_COMPLETE = 'GET_ORG_USERLIST_COMPLETE';//获取部门用户列表
//遮罩层
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';//获取待审核列表
export const SET_BASE_LOADING = 'SET_BASE_LOADING';//获取待审核列表

export const SET_USER_BREADINDEX = 'SET_USER_BREADINDEX';
export const SET_USER_BREADITEM = "SET_USER_BREADITEM";
export const SET_USER_BREADITEMINDEX = "SET_USER_BREADITEMINDEX";
export const CLOSE_USER_BREAD = 'CLOSE_USER_BREAD';
export const SET_USER_ONBOADING = 'SET_USER_ONBOADING';
export const ADD_USER_BREAD = "ADD_USER_BREAD";
export const MINUS_USER_BREAD = 'MINUS_USER_BREAD';

//改变加载
export const CHANGE_LOADING = 'CHANGE_LOADING';

//部门选择
export const OPEN_ORG_SELECT = 'OPEN_ORG_SELECT';//打开部门选择
export const CLOSE_ORG_SELECT = 'CLOSE_ORG_SELECT';//关闭
export const CHAGNE_ACTIVE_ORG = 'CHAGNE_ACTIVE_ORG';//切换部门

//页面切换
export const CHANGE_MENU = 'CHANGE_MENU';//菜单切换
// export const SEARCH_BOX_EXPAND = 'SEARCH_BOX_EXPAND';//搜索条件展开
export const SET_SEARCHINDEX = "SET_SEARCHINDEX";

//搜索处理
export const SEARCH_BUILDING = 'SEARCH_BUILDING';
export const SAVE_SEARCH_CONDITION = 'SAVE_SEARCH_CONDITION';//保存查询条件
export const CHANGE_KEYWORD = 'CHANGE_KEYWORD';
export const SEARCH_CONDITION = 'SEARCH_CONDITION';
export const SEARCH_KEYWORD = 'SEARCH_KEYWORD';
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER';
export const SEARCH_CUSTOMER_COMPLETE = 'SEARCH_CUSTOMER_COMPLETE';
// export const SEARCH_HUMANTYPE = 'SEARCH_HUMANTYPE';
// export const SEARCH_AGETYPE = 'SEARCH_AGETYPE';
// export const SEARCH_ORDERTYPE = 'SEARCH_ORDERTYPE';

//月结
export const MONTH_GETALLMONTHLIST = 'MONTH_GETALLMONTHLIST';
export const MONTH_UPDATEMONTHLIST = 'MONTH_UPDATEMONTHLIST';

export const MONTH_RECOVER = 'MONTH_RECOVER';
export const MONTH_CREATE = 'MONTH_CREATE';

export const MONTH_LAST = 'MONTH_LAST';

//黑名单
export const POST_ADDBLACKLST = "POST_ADDBLACKLST";
export const GET_BLACKLST = "GET_BLACKLST";
export const UPDATE_BLACKLST = "UPDATE_BLACKLST";

export const SEL_BLACKLIST = "SEL_BLACKLIST";

export const DELETE_BLACKINFO = "DELETE_BLACKINFO";
export const DELETE_UPDATEBLACKINFO = "DELETE_UPDATEBLACKINFO";

export const SET_VISIBLEHEAD = "SET_VISIBLEHEAD";

//职位新建
export const GET_CRATESTATION = "GET_CRATESTATION";
export const SET_STATION = "SET_STATION";
export const DELETE_STATION = "DELETE_STATION";
export const UPDATE_STATIONLIST = "UPDATE_STATIONLIST";

export const UPDATE_ORGSTATIONLIST = "UPDATE_ORGSTATIONLIST";
export const GET_CRATEORGSTATION = "GET_CRATEORGSTATION";

export const GET_STATIONTYPELIST = "GET_STATIONTYPELIST";
export const UPDATE_STATIONTYPELIST = "UPDATE_STATIONTYPELIST";

//薪酬管理
export const UPDATE_SALARYITEM = "UPDATE_SALARYITEM";

export const GET_SALARYITEM = "GET_SALARYITEM";
export const GET_SALARYLIST = "GET_SALARYLIST";
export const SET_SELSALARYLIST = "SET_SELSALARYLIST";
export const SET_SALARYINFO = "SET_SALARYINFO";
export const UPDATE_SALARYINFO = "UPDATE_SALARYINFO";
export const DELETE_SALARYINFO = "DELETE_SALARYINFO";

//社保
export const HUMAN_BECOME_STAFF = "HUMAN_BECOME_STAFF";

//离职
export const LEAVE_POSITON = "LEAVE_POSITON";

//异动
export const POST_CHANGEHUMAN = "POST_CHANGEHUMAN";

//兼职
export const HUMAN_PARTTIME_JOB_SAVE = 'HUMAN_PARTTIME_JOB_SAVE';
export const HUMAN_PARTTIME_JOB_SAVE_END = 'HUMAN_PARTTIME_JOB_SAVE_END';

//导表
export const EXPORT_MONTHFORM = "EXPORT_MONTHFORM";
export const EXPORT_HUMANFORM = "EXPORT_HUMANFORM";

//组织架构调整
export const DELETE_ORGBYID = "DELETE_ORGBYID";
export const UPDATE_DELETE_ORGBYID = "UPDATE_DELETE_ORGBYID";

export const ADD_ORG = "ADD_ORG";
export const UPDATE_ORG = "UPDATE_ORG";
export const UPDATE_ADD_ORG = "UPDATE_ADD_ORG";
export const UPDATE_UPDATE_ORG = "UPDATE_UPDATE_ORG";

//考勤
export const GET_ATTENDANCESETTINGLST = "GET_ATTENDANCESETTINGLST";
export const POST_ATTENDANCESETTINGLST = "POST_ATTENDANCESETTINGLST";
export const UPDATE_ATTENDANCESETTINGLST = "UPDATE_ATTENDANCESETTINGLST";

export const IMPORT_ATTENDANCELST = "IMPORT_ATTENDANCELST";
export const SEARCH_ATTENDANCELST = "SEARCH_ATTENDANCELST";
export const UPDATE_ATTENDANCELST = "UPDATE_ATTENDANCELST";
export const DELETE_ATTENDANCEITEM = "DELETE_ATTENDANCEITEM";
export const SEL_ATTENDANCELIST = "SEL_ATTENDANCELIST";

//行政奖惩
export const ADD_REWARDPUNISHMENT = "ADD_REWARDPUNISHMENT";
export const DELTE_REWARDPUNISHMENT = "DELTE_REWARDPUNISHMENT";
export const SEARCH_REWARDPUNISHMENT = "SEARCH_REWARDPUNISHMENT";
export const UPDATE_REWARDPUNISHMENTLIST = "UPDATE_REWARDPUNISHMENTLIST";
export const UPDATE_REWARDPUNISHHUMANLIST = "UPDATE_REWARDPUNISHHUMANLIST";

export const GETSELHUMANLIST_BYORGID = "GETSELHUMANLIST_BYORGID";//获取组织下所有员工信息
