export const ACTION_ROUTE = "RecommendToolIndex";
//字典项获取
export const DIC_GET_PARLIST = 'DIC_GET_PARLIST';
export const DIC_GET_PARLIST_COMPLETE = 'DIC_GET_PARLIST_COMPLETE';
export const DIC_GET_AREA = 'DIC_GET_AREA';
export const DIC_GET_AREA_COMPLETE = 'DIC_GET_AREA_COMPLETE';
//查询处理
export const SEARCH_XYH_BUILDING = 'SEARCH_XYH_BUILDING';//新耀行楼盘查询
export const SEARCH_XYH_BUILDING_COMPLETE = 'SEARCH_XYH_BUILDING_COMPLETE';//查询完成
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';//设置遮罩层
export const GET_BUILDING_DETAIL = 'GET_BUILDING_DETAIL';//获取楼盘详细
export const GET_BUILDING_DETAIL_COMPLETE = 'GET_BUILDING_DETAIL_COMPLETE';//获取楼盘详细完成
export const GET_BUILDING_SHOPS = 'GET_BUILDING_SHOPS';//获取商铺列表
export const GET_BUILDING_SHOPS_COMPLETE = 'GET_BUILDING_SHOPS_COMPLETE';//获取商铺列表完成
export const GET_BUILDING_SHOPS_DETAIL='GET_BUILDING_SHOPS_DETAIL';//获取商铺详细
export const GET_BUILDING_SHOPS_DETAIL_COMPLETE = 'GET_BUILDING_SHOPS_DETAIL_COMPLETE';//获取楼盘详细完成
export const DETAIL_CLOSE = 'DETAIL_CLOSE';//关闭楼盘详细
//查询结果处理
export const RESULT_BUILDING_RECOMMEND = 'RESULT_BUILDING_RECOMMEND';//楼盘推荐
//推荐相关
export const OPEN_RECOMMEND_DIALOG = 'OPEN_RECOMMEND_DIALOG';
export const CLOSE_RECOMMEND_DIALOG = 'CLOSE_RECOMMEND_DIALOG';
export const GET_RECOMMEND_LIST = 'GET_RECOMMEND_LIST';//获取推荐列表
export const GET_RECOMMEND_LIST_COMPLETE = 'GET_RECOMMEND_LIST_COMPLETE';//
export const CANCEL_RECOMMEND = 'CANCEL_RECOMMEND';//取消推荐
export const GET_MYCOMMEND_BUILDING = 'GET_MYCOMMEND_BUILDING';//获取我推荐的楼盘
export const GET_MYCOMMEND_BUILDING_COMPLETE = 'GET_MYCOMMEND_BUILDING_COMPLETE';
//导航处理
export const NAV_CHANGE = 'NAV_CHANGE';