export const APPNAME = 'XTWH';

export const DIC_ADD_GROUP = 'DIC_ADD_GROUP';
export const DIC_CANCEL_EDIT = 'DIC_CANCEL_EDIT';
export const DIC_EDIT_GROUP = 'DIC_EDIT_GROUP';
export const DIC_VIEW_GROUP = 'DIC_EDIT_GROUP';
export const DIC_SAVED_GROUP = 'DIC_SAVED_GROUP';
export const DIC_SET_CURRENT_GROUP = 'DIC_SET_CURRENT_GROUP';

export const DIC_GET_GROUPLIST_ASYNC = 'DIC_GET_GROUPLIST_ASYNC';
export const DIC_GET_GROUPLIST_START = 'DIC_GET_GROUPLIST_START';
export const DIC_GET_GROUPLIST_FINISH = 'DIC_GET_GROUPLIST_FINISH';

export const DIC_SAVE_GROUP_ASYNC = 'DIC_SAVE_GROUP_ASYNC';
export const DIC_SAVE_GROUP_START = 'DIC_SAVE_GROUP_START';
export const DIC_SAVE_GROUP_FINISH = 'DIC_SAVE_GROUP_FINISH';

export const DIC_DEL_GROUP_ASYNC = 'DIC_DEL_GROUP_ASYNC';
export const DIC_DEL_GROUP_START = 'DIC_DEL_GROUP_START';
export const DIC_DEL_GROUP_FINISH = 'DIC_DEL_GROUP_FINISH';


export const DIC_GET_PARLIST_ASYNC = 'DIC_GET_PARLIST_ASYNC';
export const DIC_GET_PARLIST_START = 'DIC_GET_PARLIST_START';
export const DIC_GET_PARLIST_FINISH = 'DIC_GET_PARLIST_FINISH';

export const DIC_ADD_VALUE = 'DIC_ADD_VALUE';
export const DIC_EDIT_VALUE = 'DIC_EDIT_VALUE';
export const DIC_VIEW_VALUE = 'DIC_VIEW_VALUE';
export const DIC_CANCEL_EDIT_VALUE = 'DIC_CANCEL_EDIT_VALUE';

export const DIC_SAVE_VALUE_ASYNC = 'DIC_SAVE_VALUE_ASYNC';
export const DIC_SAVE_VALUE_START = 'DIC_SAVE_VALUE_START';
export const DIC_SAVE_VALUE_FINISH = 'DIC_SAVE_VALUE_FINISH';

export const DIC_DEL_VALUE_ASYNC = 'DIC_DEL_VALUE_ASYNC';
export const DIC_DEL_VALUE_START = 'DIC_DEL_VALUE_START';
export const DIC_DEL_VALUE_FINISH = 'DIC_DEL_VALUE_FINISH';


export const AREA_GET_LIST_ASYNC = 'AREA_GET_LIST_ASYNC'
export const AREA_GET_LIST_START = 'AREA_GET_LIST_START'
export const AREA_GET_LIST_FINISH = 'AREA_GET_LIST_FINISH'
export const AREA_SET_CURRENT = 'AREA_SET_CURRENT'
export const AREA_DEL_ASYNC = 'AREA_DEL_ASYNC'
export const AREA_DEL_START = 'AREA_DEL_START'
export const AREA_DEL_FINISH = 'AREA_DEL_FINISH'

export const AREA_ADD = 'AREA_ADD'
export const AREA_EDIT = 'AREA_EDIT'
export const AREA_VIEW = 'AREA_VIEW'
export const AREA_CANCEL = 'AREA_CANCEL'
export const AREA_SAVE_ASYNC = 'AREA_SAVE_ASYNC'
export const AREA_SAVE_START = 'AREA_SAVE_START'
export const AREA_SAVE_FINISH = 'AREA_SAVE_FINISH'

// 启用字典项定义
export const START_DIC_VALUE_ASYNC = 'START_DIC_VALUE_ASYNC'
export const START_DIC_VALUE_START = 'START_DIC_VALUE_START'
export const START_DIC_VALUE_END = 'START_DIC_VALUE_END'

//业态规划维护
export const TRADE_PLANNING_GETLIST = 'TRADE_PLANNING_GETLIST';
export const TRADE_PLANNING_GETLIST_END = 'TRADE_PLANNING_GETLIST_COMPLETE';
export const TRADE_PLANNING_ADD = 'TRADE_PLANNING_ADD';
export const TRADE_PLANNING_ADD_END = 'TRADE_PLANNING_ADD_END';
export const TRADE_PLANNING_EDIT = 'TRADE_PLANNING_EDIT';
export const TRADE_PLANNING_EDIT_END = 'TRADE_PLANNING_EDIT_END';
export const TRADE_PLANNING_REMOVE = 'TRADE_PLANNING_REMOVE';
export const TRADE_PLANNING_REMOVE_END = 'TRADE_PLANNING_REMOVE_END';