export const ACTION_ROUTE = "ExpenseManagerIndex";

//部门获取
export const GET_ALLDEPARTMENT = 'GET_ALLDEPARTMENT';
export const CHNAGE_MENU = 'CHANGE_MENU';

//遮罩层
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
//字典获取
export const GET_CHARGEDICINFO = 'GET_CHARGEDICINFO';
export const DIC_GET_PARLIST_COMPLETE = "DIC_GET_PARLIST_COMPLETE";

export const CLOSE_USER_BREAD = "CLOSE_USER_BREAD";

//上传文件
export const UPLOAD_CHARGEFILE = "UPLOAD_CHARGEFILE";

export const POST_CHARGEINFO = "POST_CHARGEINFO";