export const ACTION_ROUTE = "ExpenseManagerIndex";

//部门获取
export const GET_ALLDEPARTMENT = 'GET_ALLDEPARTMENT';
export const DIC_GET_ALL_ORG_LIST_COMPLETE = "DIC_GET_ALL_ORG_LIST_COMPLETE;"
export const CHNAGE_MENU = 'CHANGE_MENU';

//遮罩层
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
//字典获取
export const GET_CHARGEDICINFO = 'GET_CHARGEDICINFO';
export const DIC_GET_PARLIST_COMPLETE = "DIC_GET_PARLIST_COMPLETE";

//面包屑
export const CLOSE_USER_BREAD = "CLOSE_USER_BREAD";
export const SET_USER_BREADINDEX = "SET_USER_BREADINDEX";
export const SET_USER_BREAD = "SET_USER_BREAD";
export const SET_USER_BREADADD = "SET_USER_BREADADD";

//上传文件
export const UPLOAD_CHARGEFILE = "UPLOAD_CHARGEFILE";

//提交费用信息
export const POST_CHARGEINFO = "POST_CHARGEINFO";

//搜索查询
export const POST_SEARCHCONDITION = "POST_SEARCHCONDITION";
export const UPDATE_SEARCHCONDITION = "UPDATE_SEARCHCONDITION";
export const UPDATE_SEARCHCHECKSTATU = "UPDATE_SEARCHCHECKSTATU";
export const UPDATE_SEARCHCHARGEPRICE = "UPDATE_SEARCHCHARGEPRICE";

//查询报销单
export const GET_RECIEPTBYID = "GET_RECIEPTBYID";
export const UPDATE_RECIPTINFO = "UPDATE_RECIPTINFO";

//付款
export const POST_PAYMENTCHARGE = "POST_PAYMENTCHARGE";